@startuml
!pragma teoz true
Alice -> Bob : hello
& Bob -> Charlie : hi
group A teoz group
Alice -> Bob : hello
& Bob -> Charlie : ha
end
{start} Alice -> Bob : start doing things\nduring duration
Bob -> Charlie : something
Charlie -> Bob : something else
{end} Bob -> Alice : finish
{start} <-> {end} : some time
@enduml
