
# Author: The-Lum
# Script: 
# The script generates all the `.puml` files (from all `.puml` files of the `input` directory)
# for all PlantUML theme (from `script/themes.csv`)
# on the `gallery` directory

use strict;
use warnings;
use autodie;

# Theme list
open(my $fh_t, '<', 'script/themes.csv');
my @themes = <$fh_t>;
chomp(@themes);

# Input file: all the .puml file
my @files = glob("collections/_diagrams/input/*.puml");

my $h = <<EOT;
' Do not edit
' Theme Gallery
' autogenerated by script
'
EOT

foreach my $t (@themes) {
    foreach my $f (@files) {
        open(my $fh, '<',  $f);
        (my $file_no_ext = $f) =~ s/\.[^.]+$//;
        $file_no_ext =~ s|^.*/||;
        # Output File
        open(my $fho, '>:encoding(UTF-8)', 'gallery/themed-input/' . $file_no_ext . '-' . $t . '.puml');
        print $fho $h;
        while (<$fh>) {
            $_ .= "!theme $t\n" if $. == 1;
            print $fho $_;
        }
    }
}
