
# Author: The-Lum
# Script: 
# The script generates all the `.puml` files (from all `.puml` files of the `input` directory)
# for all PlantUML skin (from `script/skin.yml`)
# on the `gallery` directory

use strict;
use warnings;
use autodie;

# Skin list
open(my $fh_t, '<', 'script/skin.yml');
my @skins = <$fh_t>;
chomp(@skins);

# Input file: all the .puml file
my @files = glob("collections/_diagrams/input/*.puml");

my $h = <<EOT;
' Do not edit
' Theme Gallery
' autogenerated by script
'
EOT

foreach my $s (@skins) {
    foreach my $f (@files) {
        open(my $fh, '<',  $f);
        (my $file_no_ext = $f) =~ s/\.[^.]+$//;
        $file_no_ext =~ s|^.*/||;
        # Output File
        open(my $fho, '>:encoding(UTF-8)', 'gallery/themed-input/' . $file_no_ext . '-' . $s . '.puml');
        print $fho $h;
        while (<$fh>) {
            $_ .= "skin $s\n" if $. == 1;
            print $fho $_;
        }
    }
}
