
# Author: The-Lum
# Script: 
# The script generates all the `.puml` files (from all `.puml` files of the `input` directory)
# for all PlantUML theme (from `lib/all_plantuml_theme.txt`)
# on the `gallery` directory

use strict;
use warnings;
use autodie;

# Theme list
open(my $fh_t, '<', 'lib/all_plantuml_theme.txt');
my @themes = <$fh_t>;
chomp(@themes);

# Input file: all the .puml file
my @files = <input/*.puml>;

my $h = <<EOT;
' Do not edit
' Theme Gallery
' autogenerated by script
EOT

foreach my $t (@themes) {
	foreach my $f (@files) {
		open(my $fh, '<',  $f); 
		(my $file_no_ext = $f) =~ s/\.[^.]+$//;
		$file_no_ext =~ s|^.*/||;
		# Output File
		open(my $fho, '>:encoding(UTF-8)', 'gallery/' . $file_no_ext . '-' . $t . '.puml');
		print $fho $h;
		while (<$fh>) {
			$_ .= "!theme $t\ntitle $t theme\n" if $. == 1;
			print $fho $_;
		}
	}
}
