name: Generate puml gallery (all puml for all theme)
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job
  job1:
    name: generate_all_puml_for_all_theme
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: Run `generate_all_puml_for_all_theme.pl`
        run: |
          mkdir -p gallery
          perl -w script/generate_all_puml_for_all_theme.pl
      # Runs  Commit the changes, if any
      - name: Commit the changes, if any
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update puml gallery
