name: Update lib with Snapshot
on:
  workflow_dispatch:

jobs:
  update_lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run `update_lib_with_snapshot`
        run: |
          chmod +x script/update_lib_with_snapshot.sh
          ./script/update_lib_with_snapshot.sh
      - name: Commit the changes, if any
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update repository with the latest snapshot lib
