name: Update lib with Snapshot, and Generate all SVG
on:
  workflow_dispatch:

jobs:
  job:
    name: Update lib with Snapshot and Generate all SVG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run `update_lib_with_snapshot`
        run: |
          chmod +x script/update_lib_with_snapshot.sh
          ./script/update_lib_with_snapshot.sh
      - name: Run `generate_all_SVG.sh`
        run: |
          chmod +x script/generate_all_SVG.sh
          ./script/generate_all_SVG.sh
      - name: Commit the changes, if any
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update repository with the latest snapshot lib and lastest SVG
